// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUSHvmTNcZqMqGyp94dNxi7n0E4M_JWJY',
    appId: '1:506124082309:web:a6bdf04ad2fe646be29dec',
    messagingSenderId: '506124082309',
    projectId: 'amigo-secreto-v2',
    authDomain: 'amigo-secreto-v2.firebaseapp.com',
    databaseURL: 'https://amigo-secreto-v2.firebaseio.com',
    storageBucket: 'amigo-secreto-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDODqs1_XuEgOBHH5u7ezIWOJ2BwdnuY',
    appId: '1:506124082309:android:16e4776ceee02799e29dec',
    messagingSenderId: '506124082309',
    projectId: 'amigo-secreto-v2',
    databaseURL: 'https://amigo-secreto-v2.firebaseio.com',
    storageBucket: 'amigo-secreto-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvh1-CwWwF5ovcq4ddCyJIyxIUjUAssQ',
    appId: '1:506124082309:ios:2646b981f40a77bfe29dec',
    messagingSenderId: '506124082309',
    projectId: 'amigo-secreto-v2',
    databaseURL: 'https://amigo-secreto-v2.firebaseio.com',
    storageBucket: 'amigo-secreto-v2.appspot.com',
    androidClientId: '506124082309-2o7ikghf6doppvt2b5s8lqs257vuclb0.apps.googleusercontent.com',
    iosClientId: '506124082309-6qtntr67fe8g2k9bg4794l9iinn0q5sb.apps.googleusercontent.com',
    iosBundleId: 'com.lsambo02.amigoSecretov2',
  );
}
